/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.BorderFactory;
import model.bean.Cliente;
import model.bean.Orcamento;
import model.dao.ClienteDAO;
import user_interface.MainFrame;
import user_interface.table_manager.TableManager;

/**
 *
 * @author Gustavo H. D. Ventura
 */
public class ClienteDialog extends javax.swing.JFrame {
    
    private int userId;
    private MainFrame mainFrame;
    private Cliente selectedClient;
    private boolean updateMode;
    private boolean fromTableManager;
    private Orcamento orcamentoHolder;
    private boolean orcamentoUpdateMode;
    
    /**
     * Creates new form ClienteDialog
     */
    public ClienteDialog() {
        initComponents();
        configure();
    }
    
    public ClienteDialog(int userId, MainFrame mainFrame, Cliente selectedClient, boolean updateMode) {
        initComponents();
        
        this.mainFrame = mainFrame;
        configure();
        
        this.selectedClient = selectedClient;
        this.updateMode = updateMode;
        this.userId = userId;
        this.fromTableManager = false;
        this.orcamentoHolder = null;
        this.orcamentoUpdateMode = false;
        
        if (updateMode) {
            setTitle("Atualização de Cliente");
            this.mainTitleTextField.setText("Atualização de Cliente");
            
            populateGui(selectedClient);
        }
    }
    
    public void setFromTableManager(boolean fromTableManager) {
        this.fromTableManager = fromTableManager;
    }
    
    public void setOrcamentoHolder(Orcamento orcamento) {
        this.orcamentoHolder = orcamento;
    }
    
    public void setOrcamentoUpdateMode(boolean orcamentoUpdateMode) {
        this.orcamentoUpdateMode = orcamentoUpdateMode;
    }
    
    private void configure() {
        dispose();
        
        setUndecorated(true);
        setDefaultCloseOperation(0);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.nameValidationLabel.setText("_");
        this.cellphoneValidationLabel.setText("_");
        this.emailValidationLabel.setText("_");
        this.addressValidationLabel.setText("_");
        
        pack();
        setLocationRelativeTo(mainFrame);
        
        setVisible(true);
    }

    private void populateGui(Cliente selectedClient) {
        this.nameTextField.setText(selectedClient.getNome());
        this.cellphoneTextField.setText(selectedClient.getTelefone());
        this.emailTextField.setText(selectedClient.getEmail());
        this.addressTextField.setText(selectedClient.getEndereco());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        mainBarPanel = new javax.swing.JPanel();
        nameInputPanel = new javax.swing.JPanel();
        nameTitlePanel = new javax.swing.JPanel();
        nameTitleLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nameValidationLabel = new javax.swing.JLabel();
        cellphoneInputPanel = new javax.swing.JPanel();
        cellphoneTitlePanel = new javax.swing.JPanel();
        cellphoneTitleLabel = new javax.swing.JLabel();
        cellphoneTextField = new javax.swing.JTextField();
        cellphoneValidationLabel = new javax.swing.JLabel();
        midLine = new javax.swing.JPanel();
        emailInputPanel = new javax.swing.JPanel();
        emailTitlePanel = new javax.swing.JPanel();
        emailTitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailValidationLabel = new javax.swing.JLabel();
        addressInputPanel = new javax.swing.JPanel();
        addressTitlePanel = new javax.swing.JPanel();
        addressTitleLabel = new javax.swing.JLabel();
        addressValidationLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        confirmPanel = new javax.swing.JPanel();
        confirmTextLabel = new javax.swing.JLabel();
        cancelarPanel = new javax.swing.JPanel();
        cancelarTextLabel = new javax.swing.JLabel();
        midBorderBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(255, 165, 0));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(180, 700));

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        topBarPanel.setBackground(new java.awt.Color(192, 192, 192));

        mainTitleTextField.setBackground(new java.awt.Color(192, 192, 192));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(255, 140, 0));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Cadastro de Cliente");
        mainTitleTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTitleTextField.setPreferredSize(new java.awt.Dimension(165, 110));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainBarPanel.setBackground(new java.awt.Color(211, 211, 211));

        nameInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        nameInputPanel.setMinimumSize(new java.awt.Dimension(290, 116));
        nameInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        nameTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        nameTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        nameTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        nameTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameTitleLabel.setText("Nome");
        nameTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout nameTitlePanelLayout = new javax.swing.GroupLayout(nameTitlePanel);
        nameTitlePanel.setLayout(nameTitlePanelLayout);
        nameTitlePanelLayout.setHorizontalGroup(
            nameTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nameTitlePanelLayout.setVerticalGroup(
            nameTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        nameTextField.setBackground(new java.awt.Color(211, 211, 211));
        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(0, 0, 0));
        nameTextField.setMinimumSize(new java.awt.Dimension(266, 30));
        nameTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        nameValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        nameValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        nameValidationLabel.setText("Máximo de caracteres para Nome é: 63 *");

        javax.swing.GroupLayout nameInputPanelLayout = new javax.swing.GroupLayout(nameInputPanel);
        nameInputPanel.setLayout(nameInputPanelLayout);
        nameInputPanelLayout.setHorizontalGroup(
            nameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(nameInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameValidationLabel))
                .addContainerGap())
        );
        nameInputPanelLayout.setVerticalGroup(
            nameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameInputPanelLayout.createSequentialGroup()
                .addComponent(nameTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        cellphoneInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        cellphoneInputPanel.setMinimumSize(new java.awt.Dimension(290, 116));
        cellphoneInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        cellphoneTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        cellphoneTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        cellphoneTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        cellphoneTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cellphoneTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        cellphoneTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellphoneTitleLabel.setText("Telefone");
        cellphoneTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cellphoneTitlePanelLayout = new javax.swing.GroupLayout(cellphoneTitlePanel);
        cellphoneTitlePanel.setLayout(cellphoneTitlePanelLayout);
        cellphoneTitlePanelLayout.setHorizontalGroup(
            cellphoneTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cellphoneTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cellphoneTitlePanelLayout.setVerticalGroup(
            cellphoneTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cellphoneTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cellphoneTextField.setBackground(new java.awt.Color(211, 211, 211));
        cellphoneTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cellphoneTextField.setForeground(new java.awt.Color(0, 0, 0));
        cellphoneTextField.setMinimumSize(new java.awt.Dimension(266, 30));
        cellphoneTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        cellphoneValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        cellphoneValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cellphoneValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        cellphoneValidationLabel.setText("Máximo de caracteres para Telefone é: 20 *");

        javax.swing.GroupLayout cellphoneInputPanelLayout = new javax.swing.GroupLayout(cellphoneInputPanel);
        cellphoneInputPanel.setLayout(cellphoneInputPanelLayout);
        cellphoneInputPanelLayout.setHorizontalGroup(
            cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cellphoneTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(cellphoneInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellphoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cellphoneInputPanelLayout.createSequentialGroup()
                        .addComponent(cellphoneValidationLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cellphoneInputPanelLayout.setVerticalGroup(
            cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cellphoneInputPanelLayout.createSequentialGroup()
                .addComponent(cellphoneTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        midLine.setBackground(new java.awt.Color(0, 0, 0));
        midLine.setForeground(new java.awt.Color(0, 0, 0));
        midLine.setMinimumSize(new java.awt.Dimension(1, 346));
        midLine.setPreferredSize(new java.awt.Dimension(1, 346));

        javax.swing.GroupLayout midLineLayout = new javax.swing.GroupLayout(midLine);
        midLine.setLayout(midLineLayout);
        midLineLayout.setHorizontalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        midLineLayout.setVerticalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        emailInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        emailInputPanel.setMinimumSize(new java.awt.Dimension(290, 116));
        emailInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        emailTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        emailTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        emailTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        emailTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailTitleLabel.setText("Email");
        emailTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout emailTitlePanelLayout = new javax.swing.GroupLayout(emailTitlePanel);
        emailTitlePanel.setLayout(emailTitlePanelLayout);
        emailTitlePanelLayout.setHorizontalGroup(
            emailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        emailTitlePanelLayout.setVerticalGroup(
            emailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        emailTextField.setBackground(new java.awt.Color(211, 211, 211));
        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(0, 0, 0));
        emailTextField.setMinimumSize(new java.awt.Dimension(266, 30));
        emailTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        emailValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        emailValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        emailValidationLabel.setText("Máximo de caracteres para Email é: 48 *");

        javax.swing.GroupLayout emailInputPanelLayout = new javax.swing.GroupLayout(emailInputPanel);
        emailInputPanel.setLayout(emailInputPanelLayout);
        emailInputPanelLayout.setHorizontalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(emailInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailValidationLabel))
                .addContainerGap())
        );
        emailInputPanelLayout.setVerticalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanelLayout.createSequentialGroup()
                .addComponent(emailTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        addressInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        addressInputPanel.setMinimumSize(new java.awt.Dimension(290, 116));

        addressTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        addressTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        addressTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        addressTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addressTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        addressTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressTitleLabel.setText("Endereço");
        addressTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout addressTitlePanelLayout = new javax.swing.GroupLayout(addressTitlePanel);
        addressTitlePanel.setLayout(addressTitlePanelLayout);
        addressTitlePanelLayout.setHorizontalGroup(
            addressTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addressTitlePanelLayout.setVerticalGroup(
            addressTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addressValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        addressValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        addressValidationLabel.setText("Máximo de caracteres para Endereço é: 72 *");
        addressValidationLabel.setPreferredSize(new java.awt.Dimension(250, 16));

        addressTextField.setBackground(new java.awt.Color(211, 211, 211));
        addressTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(0, 0, 0));
        addressTextField.setMinimumSize(new java.awt.Dimension(266, 30));
        addressTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout addressInputPanelLayout = new javax.swing.GroupLayout(addressInputPanel);
        addressInputPanel.setLayout(addressInputPanelLayout);
        addressInputPanelLayout.setHorizontalGroup(
            addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInputPanelLayout.createSequentialGroup()
                .addComponent(addressTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addressInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addressInputPanelLayout.createSequentialGroup()
                        .addComponent(addressValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addressInputPanelLayout.setVerticalGroup(
            addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInputPanelLayout.createSequentialGroup()
                .addComponent(addressTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        confirmPanel.setBackground(new java.awt.Color(192, 192, 192));
        confirmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmPanelMouseReleased(evt);
            }
        });

        confirmTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        confirmTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        confirmTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTextLabel.setText("Confirmar");
        confirmTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cancelarPanel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setForeground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        cancelarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseReleased(evt);
            }
        });

        cancelarTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        cancelarTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarTextLabel.setText("Cancelar");
        cancelarTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cancelarPanelLayout = new javax.swing.GroupLayout(cancelarPanel);
        cancelarPanel.setLayout(cancelarPanelLayout);
        cancelarPanelLayout.setHorizontalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarPanelLayout.setVerticalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midBorderBottom.setBackground(new java.awt.Color(211, 211, 211));
        midBorderBottom.setForeground(new java.awt.Color(211, 211, 211));

        javax.swing.GroupLayout midBorderBottomLayout = new javax.swing.GroupLayout(midBorderBottom);
        midBorderBottom.setLayout(midBorderBottomLayout);
        midBorderBottomLayout.setHorizontalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        midBorderBottomLayout.setVerticalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainBarPanelLayout = new javax.swing.GroupLayout(mainBarPanel);
        mainBarPanel.setLayout(mainBarPanelLayout);
        mainBarPanelLayout.setHorizontalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(midLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellphoneInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        mainBarPanelLayout.setVerticalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(midLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(midBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellphoneInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseEntered
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseEntered

    private void cancelarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseExited
        cancelarPanel.setBackground(new Color(192,192,192));
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMouseExited

    private void cancelarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMousePressed
        cancelarPanel.setBackground(Color.BLACK);
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMousePressed

    private void cancelarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseReleased
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseReleased

    private void cancelarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseClicked
        if (fromTableManager) {
            TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true); 
            tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
            tableManager.refreshViewClients(this.mainFrame, tableManager.getTable());

            tableManager.pack();
            tableManager.setLocationRelativeTo(this.mainFrame);
            dispose(); 
            tableManager.setVisible(true);
        }

        dispose();
    }//GEN-LAST:event_cancelarPanelMouseClicked

    private void confirmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseEntered
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseEntered

    private void confirmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseExited
        confirmPanel.setBackground(new Color(192,192,192));
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMouseExited

    private void confirmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMousePressed
        confirmPanel.setBackground(Color.BLACK);
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMousePressed

    private void confirmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseReleased
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseReleased

    private void confirmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseClicked
        performAction();
    }//GEN-LAST:event_confirmPanelMouseClicked

    private void performAction() {
        String name = this.nameTextField.getText();
        String cellphone = this.cellphoneTextField.getText();
        String email = this.emailTextField.getText();
        String address = this.addressTextField.getText();
        
        Cliente cliente = null;
        if (updateMode) {
            cliente = this.selectedClient;
        } else {
            cliente = new Cliente();
        }
        
        boolean invalidInput = false;
        try {
            cliente.setNome(name);
            this.nameValidationLabel.setText("_");
        } catch (IllegalArgumentException e) {
            this.nameValidationLabel.setText("Máximo de caracteres para Nome é: 63 *");
            invalidInput = true;
        } catch (NullPointerException e) {
            this.nameValidationLabel.setText("É preciso inserir um nome. *");
            invalidInput = true;
        }
        try {
            cliente.setTelefone(cellphone);
            this.cellphoneValidationLabel.setText("_");
        } catch (Exception e) {
            this.cellphoneValidationLabel.setText("Máximo de caracteres para Telefone é: 20 *");
            invalidInput = true;
        }
        try {
            cliente.setEmail(email);
            this.emailValidationLabel.setText("_");
        } catch (Exception e) {
            this.emailValidationLabel.setText("Máximo de caracteres para Email é: 48 *");
            invalidInput = true;
        }
        try {
            cliente.setEndereco(address);
            this.addressValidationLabel.setText("_");
        } catch (Exception e) {
            this.addressValidationLabel.setText("Máximo de caracteres para Endereço é: 72 *");
            invalidInput = true;
        }
        
        if (invalidInput) {
            return;
        }
        
        try {
            if (this.updateMode) {           
                new ClienteDAO().update(cliente, userId);
            } else {
                new ClienteDAO().create(cliente);
            }
            
            if (mainFrame != null && !fromTableManager) {
                this.mainFrame.refreshView("Clientes", null);
                dispose(); 
            } else {
                TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true);
                tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
                tableManager.refreshViewClients(this.mainFrame, tableManager.getTable());

                tableManager.pack();
                tableManager.setLocationRelativeTo(this.mainFrame);
                dispose(); 
                tableManager.setVisible(true);
            }
        } catch (HeadlessException ex) {
            System.err.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClienteDialog();
                } catch (Exception e) {
                    e.printStackTrace();
                }        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressInputPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel addressTitleLabel;
    private javax.swing.JPanel addressTitlePanel;
    private javax.swing.JLabel addressValidationLabel;
    private javax.swing.JPanel cancelarPanel;
    private javax.swing.JLabel cancelarTextLabel;
    private javax.swing.JPanel cellphoneInputPanel;
    private javax.swing.JTextField cellphoneTextField;
    private javax.swing.JLabel cellphoneTitleLabel;
    private javax.swing.JPanel cellphoneTitlePanel;
    private javax.swing.JLabel cellphoneValidationLabel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel confirmTextLabel;
    private javax.swing.JPanel emailInputPanel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emailTitleLabel;
    private javax.swing.JPanel emailTitlePanel;
    private javax.swing.JLabel emailValidationLabel;
    private javax.swing.JPanel mainBarPanel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPanel midBorderBottom;
    private javax.swing.JPanel midLine;
    private javax.swing.JPanel nameInputPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nameTitleLabel;
    private javax.swing.JPanel nameTitlePanel;
    private javax.swing.JLabel nameValidationLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
