/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.BorderFactory;
import model.bean.Config;
import model.dao.ConfigDAO;
import user_interface.MainFrame;

/**
 *
 * @author Gustavo H. D. Ventura
 */
public class ConfigDialog extends javax.swing.JFrame {
    
    private int userId;
    private MainFrame mainFrame;
    private Config selectedConfig;
    
    /**
     * Creates new form ConfigDialog
     */
    public ConfigDialog() {
        initComponents();
        configure();
    }
    
    public ConfigDialog(MainFrame mainFrame) {
        initComponents();
        configure();
        
        this.selectedConfig = new ConfigDAO().read();
        this.mainFrame = mainFrame;
        
        populateGui(selectedConfig);
    }
    
    private void configure() {
        dispose();
        
        setUndecorated(true);
        setDefaultCloseOperation(0);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.emailValidationLabel.setText("");
        this.cellphoneValidationLabel.setText("");
        this.addressValidationLabel.setText("");
        
        pack();
        setLocationRelativeTo(mainFrame);
        
        setVisible(true);
    }

    private void populateGui(Config config) {
        this.companyNameTextField.setText(config.getCompanyName());
        this.cellphoneTextField.setText(config.getCellphone());
        this.emailTextField.setText(config.getEmail());
        this.addressTextField.setText(config.getAddress());    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        mainBarPanel = new javax.swing.JPanel();
        emailInputPanel = new javax.swing.JPanel();
        emailTitlePanel = new javax.swing.JPanel();
        descriptionTitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailValidationLabel = new javax.swing.JLabel();
        companyNameInputPanel = new javax.swing.JPanel();
        companyNameTitlePanel = new javax.swing.JPanel();
        fuelTypeTitleLabel = new javax.swing.JLabel();
        companyNameTextField = new javax.swing.JTextField();
        midLine = new javax.swing.JPanel();
        cellphoneInputPanel = new javax.swing.JPanel();
        cellphoneTitlePanel = new javax.swing.JPanel();
        licensePlateTitleLabel = new javax.swing.JLabel();
        cellphoneTextField = new javax.swing.JTextField();
        cellphoneValidationLabel = new javax.swing.JLabel();
        confirmPanel = new javax.swing.JPanel();
        confirmTextLabel = new javax.swing.JLabel();
        cancelarPanel = new javax.swing.JPanel();
        cancelarTextLabel = new javax.swing.JLabel();
        midBorderBottom = new javax.swing.JPanel();
        addressInputPanel = new javax.swing.JPanel();
        addressTitlePanel = new javax.swing.JPanel();
        colorTitleLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        addressValidationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações gerais");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(255, 165, 0));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(180, 700));

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        topBarPanel.setBackground(new java.awt.Color(192, 192, 192));

        mainTitleTextField.setBackground(new java.awt.Color(192, 192, 192));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(255, 140, 0));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Configurações gerais");
        mainTitleTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTitleTextField.setPreferredSize(new java.awt.Dimension(165, 110));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainBarPanel.setBackground(new java.awt.Color(211, 211, 211));

        emailInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        emailInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        emailTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        emailTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        descriptionTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        descriptionTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionTitleLabel.setText("Email");
        descriptionTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout emailTitlePanelLayout = new javax.swing.GroupLayout(emailTitlePanel);
        emailTitlePanel.setLayout(emailTitlePanelLayout);
        emailTitlePanelLayout.setHorizontalGroup(
            emailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        emailTitlePanelLayout.setVerticalGroup(
            emailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        emailTextField.setBackground(new java.awt.Color(211, 211, 211));
        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(0, 0, 0));
        emailTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        emailValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        emailValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        emailValidationLabel.setText("Máximo de caracteres para Email é: 48 *");

        javax.swing.GroupLayout emailInputPanelLayout = new javax.swing.GroupLayout(emailInputPanel);
        emailInputPanel.setLayout(emailInputPanelLayout);
        emailInputPanelLayout.setHorizontalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emailTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(emailInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailValidationLabel))
                .addContainerGap())
        );
        emailInputPanelLayout.setVerticalGroup(
            emailInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailInputPanelLayout.createSequentialGroup()
                .addComponent(emailTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        companyNameInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        companyNameInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        companyNameTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        companyNameTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        fuelTypeTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        fuelTypeTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelTypeTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        fuelTypeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelTypeTitleLabel.setText("Nome da empresa");
        fuelTypeTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout companyNameTitlePanelLayout = new javax.swing.GroupLayout(companyNameTitlePanel);
        companyNameTitlePanel.setLayout(companyNameTitlePanelLayout);
        companyNameTitlePanelLayout.setHorizontalGroup(
            companyNameTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelTypeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        companyNameTitlePanelLayout.setVerticalGroup(
            companyNameTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelTypeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        companyNameTextField.setBackground(new java.awt.Color(211, 211, 211));
        companyNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        companyNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        companyNameTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout companyNameInputPanelLayout = new javax.swing.GroupLayout(companyNameInputPanel);
        companyNameInputPanel.setLayout(companyNameInputPanelLayout);
        companyNameInputPanelLayout.setHorizontalGroup(
            companyNameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(companyNameTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(companyNameInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        companyNameInputPanelLayout.setVerticalGroup(
            companyNameInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyNameInputPanelLayout.createSequentialGroup()
                .addComponent(companyNameTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        midLine.setBackground(new java.awt.Color(0, 0, 0));
        midLine.setForeground(new java.awt.Color(0, 0, 0));
        midLine.setMinimumSize(new java.awt.Dimension(1, 346));
        midLine.setPreferredSize(new java.awt.Dimension(1, 346));

        javax.swing.GroupLayout midLineLayout = new javax.swing.GroupLayout(midLine);
        midLine.setLayout(midLineLayout);
        midLineLayout.setHorizontalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        midLineLayout.setVerticalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        cellphoneInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        cellphoneInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        cellphoneTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        cellphoneTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        licensePlateTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        licensePlateTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        licensePlateTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        licensePlateTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licensePlateTitleLabel.setText("Telefone");
        licensePlateTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cellphoneTitlePanelLayout = new javax.swing.GroupLayout(cellphoneTitlePanel);
        cellphoneTitlePanel.setLayout(cellphoneTitlePanelLayout);
        cellphoneTitlePanelLayout.setHorizontalGroup(
            cellphoneTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(licensePlateTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cellphoneTitlePanelLayout.setVerticalGroup(
            cellphoneTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(licensePlateTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cellphoneTextField.setBackground(new java.awt.Color(211, 211, 211));
        cellphoneTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cellphoneTextField.setForeground(new java.awt.Color(0, 0, 0));
        cellphoneTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        cellphoneValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        cellphoneValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cellphoneValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        cellphoneValidationLabel.setText("Máximo de caracteres para Telefone é: 20 *");

        javax.swing.GroupLayout cellphoneInputPanelLayout = new javax.swing.GroupLayout(cellphoneInputPanel);
        cellphoneInputPanel.setLayout(cellphoneInputPanelLayout);
        cellphoneInputPanelLayout.setHorizontalGroup(
            cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cellphoneTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(cellphoneInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellphoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cellphoneValidationLabel))
                .addContainerGap())
        );
        cellphoneInputPanelLayout.setVerticalGroup(
            cellphoneInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cellphoneInputPanelLayout.createSequentialGroup()
                .addComponent(cellphoneTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        confirmPanel.setBackground(new java.awt.Color(192, 192, 192));
        confirmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmPanelMouseReleased(evt);
            }
        });

        confirmTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        confirmTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        confirmTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTextLabel.setText("Confirmar");
        confirmTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cancelarPanel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setForeground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        cancelarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseReleased(evt);
            }
        });

        cancelarTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        cancelarTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarTextLabel.setText("Cancelar");
        cancelarTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cancelarPanelLayout = new javax.swing.GroupLayout(cancelarPanel);
        cancelarPanel.setLayout(cancelarPanelLayout);
        cancelarPanelLayout.setHorizontalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarPanelLayout.setVerticalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midBorderBottom.setBackground(new java.awt.Color(211, 211, 211));
        midBorderBottom.setForeground(new java.awt.Color(211, 211, 211));

        javax.swing.GroupLayout midBorderBottomLayout = new javax.swing.GroupLayout(midBorderBottom);
        midBorderBottom.setLayout(midBorderBottomLayout);
        midBorderBottomLayout.setHorizontalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        midBorderBottomLayout.setVerticalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addressInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        addressInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        addressTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        addressTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        colorTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        colorTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colorTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        colorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorTitleLabel.setText("Endereço");
        colorTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout addressTitlePanelLayout = new javax.swing.GroupLayout(addressTitlePanel);
        addressTitlePanel.setLayout(addressTitlePanelLayout);
        addressTitlePanelLayout.setHorizontalGroup(
            addressTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addressTitlePanelLayout.setVerticalGroup(
            addressTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addressTextField.setBackground(new java.awt.Color(211, 211, 211));
        addressTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(0, 0, 0));
        addressTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        addressValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        addressValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        addressValidationLabel.setText("Máximo de caracteres para Endereço é: 72 *");

        javax.swing.GroupLayout addressInputPanelLayout = new javax.swing.GroupLayout(addressInputPanel);
        addressInputPanel.setLayout(addressInputPanelLayout);
        addressInputPanelLayout.setHorizontalGroup(
            addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addressTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(addressInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressValidationLabel))
                .addContainerGap())
        );
        addressInputPanelLayout.setVerticalGroup(
            addressInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressInputPanelLayout.createSequentialGroup()
                .addComponent(addressTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainBarPanelLayout = new javax.swing.GroupLayout(mainBarPanel);
        mainBarPanel.setLayout(mainBarPanelLayout);
        mainBarPanelLayout.setHorizontalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellphoneInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(midLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyNameInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        mainBarPanelLayout.setVerticalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyNameInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainBarPanelLayout.createSequentialGroup()
                                .addComponent(cellphoneInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addComponent(midLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(midBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseEntered
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseEntered

    private void cancelarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseExited
        cancelarPanel.setBackground(new Color(192,192,192));
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMouseExited

    private void cancelarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMousePressed
        cancelarPanel.setBackground(Color.BLACK);
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMousePressed

    private void cancelarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseReleased
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseReleased

    private void cancelarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarPanelMouseClicked

    private void confirmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseEntered
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseEntered

    private void confirmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseExited
        confirmPanel.setBackground(new Color(192,192,192));
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMouseExited

    private void confirmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMousePressed
        confirmPanel.setBackground(Color.BLACK);
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMousePressed

    private void confirmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseReleased
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseReleased

    private void confirmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseClicked
        performAction();
    }//GEN-LAST:event_confirmPanelMouseClicked

    private void performAction() {
        String companyName = this.companyNameTextField.getText();
        String cellphone = this.cellphoneTextField.getText();
        String email = this.emailTextField.getText();
        String address = this.addressTextField.getText();
        
        Config config = this.selectedConfig;
            
        config.setCompanyName(companyName);
        this.emailValidationLabel.setText("");
        this.cellphoneValidationLabel.setText("");
        this.addressValidationLabel.setText("");
        
        boolean invalidInput = false;
        try {
            config.setCellphone(cellphone);
            this.cellphoneValidationLabel.setText("");
        } catch (Exception e) {
            this.cellphoneValidationLabel.setText("Máximo de caracteres para Telefone é: 20 *");
            invalidInput = true;
        }
        try {
            config.setEmail(email);
            this.emailValidationLabel.setText("");
        } catch (Exception e) {
            this.emailValidationLabel.setText("Máximo de caracteres para Email é: 48 *");
            invalidInput = true;
        }
        try {
            config.setAddress(address);
            this.addressValidationLabel.setText("");
        } catch (Exception e) {
            this.addressValidationLabel.setText("Máximo de caracteres para Endereço é: 72 *");
            invalidInput = true;
        }
        
        if (invalidInput) {
            return;
        }

        try {        
            new ConfigDAO().update(config);
            
            this.mainFrame.setCompanyName(companyName);
            setVisible(false);
            dispose(); 
        } catch (HeadlessException ex) {
            System.err.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConfigDialog();
                } catch (Exception e) {
                    e.printStackTrace();
                }        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressInputPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel addressTitlePanel;
    private javax.swing.JLabel addressValidationLabel;
    private javax.swing.JPanel cancelarPanel;
    private javax.swing.JLabel cancelarTextLabel;
    private javax.swing.JPanel cellphoneInputPanel;
    private javax.swing.JTextField cellphoneTextField;
    private javax.swing.JPanel cellphoneTitlePanel;
    private javax.swing.JLabel cellphoneValidationLabel;
    private javax.swing.JLabel colorTitleLabel;
    private javax.swing.JPanel companyNameInputPanel;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JPanel companyNameTitlePanel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel confirmTextLabel;
    private javax.swing.JLabel descriptionTitleLabel;
    private javax.swing.JPanel emailInputPanel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel emailTitlePanel;
    private javax.swing.JLabel emailValidationLabel;
    private javax.swing.JLabel fuelTypeTitleLabel;
    private javax.swing.JLabel licensePlateTitleLabel;
    private javax.swing.JPanel mainBarPanel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPanel midBorderBottom;
    private javax.swing.JPanel midLine;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
