/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.awt.HeadlessException;
import java.math.BigDecimal;
import javax.swing.BorderFactory;
import model.bean.Orcamento;
import model.bean.Servico;
import model.dao.ServicoDAO;
import user_interface.MainFrame;
import user_interface.table_manager.TableManager;


/**
 *
 * @author Gustavo H. D. Ventura
 */
public class ServicoDialog extends javax.swing.JFrame {
    
    private int userId;
    private MainFrame mainFrame;
    private Servico selectedService;
    private boolean updateMode;
    private boolean fromTableManager;
    private Orcamento orcamentoHolder;
    private boolean orcamentoUpdateMode;
    
    /**
     * Creates new form ServicoDialog
     */
    public ServicoDialog() {
        initComponents();
        configure();
    }
    
    public ServicoDialog(int userId, MainFrame mainFrame, Servico selectedService, boolean updateMode) {
        initComponents();
        configure();
        setLocationRelativeTo(mainFrame);
        
        this.mainFrame = mainFrame;
        this.selectedService = selectedService;
        this.updateMode = updateMode;
        this.userId = userId;
        this.fromTableManager = false;
        this.orcamentoHolder = null;
        this.orcamentoUpdateMode = false;
        
        if (updateMode) {
            setTitle("Atualização de Serviço");
            this.mainTitleTextField.setText("Atualização de Serviço");
            
            populateGui(selectedService);
        }
    }
    
    public void setFromTableManager(boolean fromTableManager) {
        this.fromTableManager = fromTableManager;
    }
    
    public void setOrcamentoHolder(Orcamento orcamento) {
        this.orcamentoHolder = orcamento;
    }
    
    public void setOrcamentoUpdateMode(boolean orcamentoUpdateMode) {
        this.orcamentoUpdateMode = orcamentoUpdateMode;
    }
    
    private void configure() {
        dispose();
        
        setUndecorated(true);
        setDefaultCloseOperation(0);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.descriptionValidationLabel.setText("_");
        this.amoutValidationLabel.setText("_");
        this.unitValidationLabel.setText("_");
        
        pack();
        
        setVisible(true);
    }

    private void populateGui(Servico selectedService) {
        this.descriptionTextField.setText(selectedService.getDescricao());
        this.unitTextField.setText(selectedService.getValorUnitarioFormated());
        this.amoutTextField.setText(selectedService.getQuantidadeFormated());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        mainBarPanel = new javax.swing.JPanel();
        descriptionInputPanel = new javax.swing.JPanel();
        descriptionTitlePanel = new javax.swing.JPanel();
        descriptionTitleLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        descriptionValidationLabel = new javax.swing.JLabel();
        unitInputPanel = new javax.swing.JPanel();
        unitTitlePanel = new javax.swing.JPanel();
        unitTitleLabel = new javax.swing.JLabel();
        unitTextField = new javax.swing.JTextField();
        unitValidationLabel = new javax.swing.JLabel();
        midLine = new javax.swing.JPanel();
        amoutInputPanel = new javax.swing.JPanel();
        amoutTitlePanel = new javax.swing.JPanel();
        amoutTitleLabel = new javax.swing.JLabel();
        amoutValidationLabel = new javax.swing.JLabel();
        amoutTextField = new javax.swing.JTextField();
        confirmPanel = new javax.swing.JPanel();
        confirmTextLabel = new javax.swing.JLabel();
        cancelarPanel = new javax.swing.JPanel();
        cancelarTextLabel = new javax.swing.JLabel();
        midBorderBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Serviço");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(255, 165, 0));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(180, 700));

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        topBarPanel.setBackground(new java.awt.Color(192, 192, 192));

        mainTitleTextField.setBackground(new java.awt.Color(192, 192, 192));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(255, 140, 0));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Cadastro de Serviço");
        mainTitleTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTitleTextField.setPreferredSize(new java.awt.Dimension(165, 110));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainBarPanel.setBackground(new java.awt.Color(211, 211, 211));

        descriptionInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        descriptionInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        descriptionTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        descriptionTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        descriptionTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        descriptionTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionTitleLabel.setText("Descrição");
        descriptionTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout descriptionTitlePanelLayout = new javax.swing.GroupLayout(descriptionTitlePanel);
        descriptionTitlePanel.setLayout(descriptionTitlePanelLayout);
        descriptionTitlePanelLayout.setHorizontalGroup(
            descriptionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        descriptionTitlePanelLayout.setVerticalGroup(
            descriptionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        descriptionTextField.setBackground(new java.awt.Color(211, 211, 211));
        descriptionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTextField.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        descriptionValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        descriptionValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descriptionValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        descriptionValidationLabel.setText("Máximo de caracteres para Descrição é: 66 *");

        javax.swing.GroupLayout descriptionInputPanelLayout = new javax.swing.GroupLayout(descriptionInputPanel);
        descriptionInputPanel.setLayout(descriptionInputPanelLayout);
        descriptionInputPanelLayout.setHorizontalGroup(
            descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(descriptionInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionValidationLabel))
                .addContainerGap())
        );
        descriptionInputPanelLayout.setVerticalGroup(
            descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionInputPanelLayout.createSequentialGroup()
                .addComponent(descriptionTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        unitInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        unitInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        unitTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        unitTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        unitTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        unitTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unitTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        unitTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unitTitleLabel.setText("Valor unitário");
        unitTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout unitTitlePanelLayout = new javax.swing.GroupLayout(unitTitlePanel);
        unitTitlePanel.setLayout(unitTitlePanelLayout);
        unitTitlePanelLayout.setHorizontalGroup(
            unitTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unitTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        unitTitlePanelLayout.setVerticalGroup(
            unitTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unitTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        unitTextField.setBackground(new java.awt.Color(211, 211, 211));
        unitTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitTextField.setForeground(new java.awt.Color(0, 0, 0));
        unitTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        unitValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        unitValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unitValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        unitValidationLabel.setText("Valor unitário inválido *");

        javax.swing.GroupLayout unitInputPanelLayout = new javax.swing.GroupLayout(unitInputPanel);
        unitInputPanel.setLayout(unitInputPanelLayout);
        unitInputPanelLayout.setHorizontalGroup(
            unitInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unitTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(unitInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unitInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(unitInputPanelLayout.createSequentialGroup()
                        .addComponent(unitValidationLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        unitInputPanelLayout.setVerticalGroup(
            unitInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unitInputPanelLayout.createSequentialGroup()
                .addComponent(unitTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        midLine.setBackground(new java.awt.Color(0, 0, 0));
        midLine.setForeground(new java.awt.Color(0, 0, 0));
        midLine.setMinimumSize(new java.awt.Dimension(1, 346));
        midLine.setPreferredSize(new java.awt.Dimension(1, 346));

        javax.swing.GroupLayout midLineLayout = new javax.swing.GroupLayout(midLine);
        midLine.setLayout(midLineLayout);
        midLineLayout.setHorizontalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        midLineLayout.setVerticalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        amoutInputPanel.setBackground(new java.awt.Color(192, 192, 192));

        amoutTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        amoutTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        amoutTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        amoutTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amoutTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        amoutTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amoutTitleLabel.setText("Quantidade");
        amoutTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout amoutTitlePanelLayout = new javax.swing.GroupLayout(amoutTitlePanel);
        amoutTitlePanel.setLayout(amoutTitlePanelLayout);
        amoutTitlePanelLayout.setHorizontalGroup(
            amoutTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amoutTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        amoutTitlePanelLayout.setVerticalGroup(
            amoutTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amoutTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        amoutValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        amoutValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amoutValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        amoutValidationLabel.setText("Quantidade inválida *");

        amoutTextField.setBackground(new java.awt.Color(211, 211, 211));
        amoutTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amoutTextField.setForeground(new java.awt.Color(0, 0, 0));
        amoutTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout amoutInputPanelLayout = new javax.swing.GroupLayout(amoutInputPanel);
        amoutInputPanel.setLayout(amoutInputPanelLayout);
        amoutInputPanelLayout.setHorizontalGroup(
            amoutInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amoutInputPanelLayout.createSequentialGroup()
                .addComponent(amoutTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(amoutInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(amoutInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(amoutInputPanelLayout.createSequentialGroup()
                        .addComponent(amoutValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(amoutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        amoutInputPanelLayout.setVerticalGroup(
            amoutInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amoutInputPanelLayout.createSequentialGroup()
                .addComponent(amoutTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amoutValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        confirmPanel.setBackground(new java.awt.Color(192, 192, 192));
        confirmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmPanelMouseReleased(evt);
            }
        });

        confirmTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        confirmTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        confirmTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTextLabel.setText("Confirmar");
        confirmTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cancelarPanel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setForeground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        cancelarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseReleased(evt);
            }
        });

        cancelarTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        cancelarTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarTextLabel.setText("Cancelar");
        cancelarTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cancelarPanelLayout = new javax.swing.GroupLayout(cancelarPanel);
        cancelarPanel.setLayout(cancelarPanelLayout);
        cancelarPanelLayout.setHorizontalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarPanelLayout.setVerticalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midBorderBottom.setBackground(new java.awt.Color(211, 211, 211));
        midBorderBottom.setForeground(new java.awt.Color(211, 211, 211));

        javax.swing.GroupLayout midBorderBottomLayout = new javax.swing.GroupLayout(midBorderBottom);
        midBorderBottom.setLayout(midBorderBottomLayout);
        midBorderBottomLayout.setHorizontalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        midBorderBottomLayout.setVerticalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainBarPanelLayout = new javax.swing.GroupLayout(mainBarPanel);
        mainBarPanel.setLayout(mainBarPanelLayout);
        mainBarPanelLayout.setHorizontalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(midLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amoutInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        mainBarPanelLayout.setVerticalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(midLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(midBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(unitInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(amoutInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(descriptionInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseEntered
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseEntered

    private void cancelarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseExited
        cancelarPanel.setBackground(new Color(192,192,192));
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMouseExited

    private void cancelarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMousePressed
        cancelarPanel.setBackground(Color.BLACK);
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMousePressed

    private void cancelarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseReleased
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseReleased

    private void cancelarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseClicked
        if (fromTableManager) {
            TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true);
            tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
            tableManager.refreshViewServices(this.mainFrame, tableManager.getTable());

            tableManager.pack();
            tableManager.setLocationRelativeTo(this.mainFrame);
            dispose(); 
            tableManager.setVisible(true);
        }

        dispose();
    }//GEN-LAST:event_cancelarPanelMouseClicked

    private void confirmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseEntered
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseEntered

    private void confirmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseExited
        confirmPanel.setBackground(new Color(192,192,192));
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMouseExited

    private void confirmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMousePressed
        confirmPanel.setBackground(Color.BLACK);
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMousePressed

    private void confirmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseReleased
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseReleased

    private void confirmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseClicked
        performAction();
    }//GEN-LAST:event_confirmPanelMouseClicked

    private void performAction() {
        String description = this.descriptionTextField.getText();
        
        Servico servico = null;
        if (updateMode) {
            servico = this.selectedService;
        } else {
            servico = new Servico();
        }
        
        boolean invalidInput = false;
        try {
            servico.setDescricao(description);
            this.descriptionValidationLabel.setText("_");
        } catch (IllegalArgumentException e) {
            this.descriptionValidationLabel.setText("Máximo de caracteres para Descrição é: 66 *");
            invalidInput = true;
        } catch (NullPointerException e) {
            this.descriptionValidationLabel.setText("É preciso inserir uma descrição do serviço. *");
            invalidInput = true;
        }
        try {
            BigDecimal unit = new BigDecimal(this.unitTextField.getText().replace(",", "."));
            servico.setValorUnitario(unit);
            this.unitValidationLabel.setText("_");
        } catch (Exception e) {
            this.unitValidationLabel.setText("Valor unitário inválido *");
            invalidInput = true;
        }
        try {
            int amout = Integer.parseInt(this.amoutTextField.getText());
            servico.setQuantidade(amout);
            this.amoutValidationLabel.setText("_");
        } catch (Exception e) {
            this.amoutValidationLabel.setText("Quantidade inválida *");
            invalidInput = true;
        }
        
        if (invalidInput) {
            return;
        }
        
        try {
            if (this.updateMode) {           
                new ServicoDAO().update(servico, userId);
            } else {
                new ServicoDAO().create(servico);
            }
            
            if (mainFrame != null && !fromTableManager) {
                this.mainFrame.refreshView("Serviços", null);
                dispose();
            } else {
                TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true);
                tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
                tableManager.refreshViewServices(this.mainFrame, tableManager.getTable());

                tableManager.pack();
                tableManager.setLocationRelativeTo(this.mainFrame);
                dispose(); 
                tableManager.setVisible(true);
            }
        } catch (HeadlessException ex) {
            System.err.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ServicoDialog();
                } catch (Exception e) {
                    e.printStackTrace();
                }        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amoutInputPanel;
    private javax.swing.JTextField amoutTextField;
    private javax.swing.JLabel amoutTitleLabel;
    private javax.swing.JPanel amoutTitlePanel;
    private javax.swing.JLabel amoutValidationLabel;
    private javax.swing.JPanel cancelarPanel;
    private javax.swing.JLabel cancelarTextLabel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel confirmTextLabel;
    private javax.swing.JPanel descriptionInputPanel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel descriptionTitleLabel;
    private javax.swing.JPanel descriptionTitlePanel;
    private javax.swing.JLabel descriptionValidationLabel;
    private javax.swing.JPanel mainBarPanel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPanel midBorderBottom;
    private javax.swing.JPanel midLine;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel topBarPanel;
    private javax.swing.JPanel unitInputPanel;
    private javax.swing.JTextField unitTextField;
    private javax.swing.JLabel unitTitleLabel;
    private javax.swing.JPanel unitTitlePanel;
    private javax.swing.JLabel unitValidationLabel;
    // End of variables declaration//GEN-END:variables
}
