/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.bean.User;
import model.dao.UserDAO;
import model.util.PasswordsUtil;
import user_interface.MainFrame;

/**
 *
 * @author Gustavo H. D. Ventura
 */
public final class UserLoginDialog extends javax.swing.JFrame {
    
    /**
     * Creates new form UserLoginDialog
     */
    public UserLoginDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        leftBarPanel = new javax.swing.JPanel();
        rightBarPanel = new javax.swing.JPanel();
        loginComboBox = new javax.swing.JComboBox<>();
        passwordTextField = new javax.swing.JPasswordField();
        loginBarPanel = new javax.swing.JPanel();
        loginTextLabel = new javax.swing.JLabel();
        registerBarPanel = new javax.swing.JPanel();
        registerTextLabel = new javax.swing.JLabel();
        blackBar1 = new javax.swing.JPanel();
        blackBar2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        setBackground(new java.awt.Color(211, 211, 211));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);

        topBarPanel.setBackground(new java.awt.Color(255, 165, 0));

        mainTitleTextField.setBackground(new java.awt.Color(255, 165, 0));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(28, 28, 28));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Conecte-se");

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        leftBarPanel.setBackground(new java.awt.Color(255, 140, 0));
        leftBarPanel.setMinimumSize(new java.awt.Dimension(50, 394));
        leftBarPanel.setPreferredSize(new java.awt.Dimension(50, 394));

        javax.swing.GroupLayout leftBarPanelLayout = new javax.swing.GroupLayout(leftBarPanel);
        leftBarPanel.setLayout(leftBarPanelLayout);
        leftBarPanelLayout.setHorizontalGroup(
            leftBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        leftBarPanelLayout.setVerticalGroup(
            leftBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        rightBarPanel.setBackground(new java.awt.Color(255, 140, 0));
        rightBarPanel.setMinimumSize(new java.awt.Dimension(50, 394));
        rightBarPanel.setPreferredSize(new java.awt.Dimension(50, 394));

        javax.swing.GroupLayout rightBarPanelLayout = new javax.swing.GroupLayout(rightBarPanel);
        rightBarPanel.setLayout(rightBarPanelLayout);
        rightBarPanelLayout.setHorizontalGroup(
            rightBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        rightBarPanelLayout.setVerticalGroup(
            rightBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        loginComboBox.setBackground(new java.awt.Color(192, 192, 192));
        loginComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginComboBox.setForeground(new java.awt.Color(0, 0, 0));
        loginComboBox.setPreferredSize(new java.awt.Dimension(290, 40));

        passwordTextField.setBackground(new java.awt.Color(192, 192, 192));
        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(0, 0, 0));
        passwordTextField.setPreferredSize(new java.awt.Dimension(290, 40));

        loginBarPanel.setBackground(new java.awt.Color(192, 192, 192));
        loginBarPanel.setForeground(new java.awt.Color(255, 140, 0));
        loginBarPanel.setMinimumSize(new java.awt.Dimension(290, 40));
        loginBarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        loginBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginBarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBarPanelMouseReleased(evt);
            }
        });

        loginTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        loginTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        loginTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTextLabel.setText("Entrar");
        loginTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout loginBarPanelLayout = new javax.swing.GroupLayout(loginBarPanel);
        loginBarPanel.setLayout(loginBarPanelLayout);
        loginBarPanelLayout.setHorizontalGroup(
            loginBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        loginBarPanelLayout.setVerticalGroup(
            loginBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        registerBarPanel.setBackground(new java.awt.Color(192, 192, 192));
        registerBarPanel.setForeground(new java.awt.Color(255, 140, 0));
        registerBarPanel.setMinimumSize(new java.awt.Dimension(290, 40));
        registerBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerBarPanelMouseReleased(evt);
            }
        });

        registerTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        registerTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        registerTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerTextLabel.setText("Cadastrar-se");
        registerTextLabel.setMaximumSize(new java.awt.Dimension(290, 40));
        registerTextLabel.setMinimumSize(new java.awt.Dimension(290, 40));
        registerTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout registerBarPanelLayout = new javax.swing.GroupLayout(registerBarPanel);
        registerBarPanel.setLayout(registerBarPanelLayout);
        registerBarPanelLayout.setHorizontalGroup(
            registerBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registerBarPanelLayout.setVerticalGroup(
            registerBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        blackBar1.setBackground(new java.awt.Color(0, 0, 0));
        blackBar1.setForeground(new java.awt.Color(0, 0, 0));
        blackBar1.setMaximumSize(new java.awt.Dimension(290, 1));
        blackBar1.setMinimumSize(new java.awt.Dimension(290, 1));
        blackBar1.setPreferredSize(new java.awt.Dimension(290, 1));

        javax.swing.GroupLayout blackBar1Layout = new javax.swing.GroupLayout(blackBar1);
        blackBar1.setLayout(blackBar1Layout);
        blackBar1Layout.setHorizontalGroup(
            blackBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        blackBar1Layout.setVerticalGroup(
            blackBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        blackBar2.setBackground(new java.awt.Color(0, 0, 0));
        blackBar2.setForeground(new java.awt.Color(0, 0, 0));
        blackBar2.setPreferredSize(new java.awt.Dimension(290, 1));

        javax.swing.GroupLayout blackBar2Layout = new javax.swing.GroupLayout(blackBar2);
        blackBar2.setLayout(blackBar2Layout);
        blackBar2Layout.setHorizontalGroup(
            blackBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        blackBar2Layout.setVerticalGroup(
            blackBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blackBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blackBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leftBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(loginComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(loginBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blackBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blackBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registerBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBarPanelMouseClicked
        if (loginComboBox.getSelectedIndex() == -1) {						
            JOptionPane.showMessageDialog(UserLoginDialog.this, "Você deve selecionar um usuário.", "Error", JOptionPane.ERROR_MESSAGE);				
            return;
        }
						
	User user = (User) loginComboBox.getSelectedItem();
	int userId = user.getId();
        String userName = user.getLogin();
        boolean userAdmin = user.isAdmin();
        
	String password = passwordTextField.getText();
        String encryptedPassword = user.getPassword();
        boolean validPassword = PasswordsUtil.checkPassword(password, encryptedPassword);

        if (validPassword) {
            setVisible(false);
            dispose();

            MainFrame frame = new MainFrame(userId, userAdmin);
            frame.setLoggedInUserName(userName);
            
            frame.setLocationRelativeTo(UserLoginDialog.this);
            
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(UserLoginDialog.this, "Senha inválida", "Error", JOptionPane.ERROR_MESSAGE);	
        }
    }//GEN-LAST:event_loginBarPanelMouseClicked

    private void registerBarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBarPanelMouseClicked
        UserDialog dialog = new UserDialog(UserLoginDialog.this);
        
        dialog.pack();
        dialog.setLocationRelativeTo(dialog);
        dialog.setVisible(true);
    }//GEN-LAST:event_registerBarPanelMouseClicked

    private void loginBarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBarPanelMouseEntered
        loginBarPanel.setBackground(new Color(255,69,0));
        loginTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_loginBarPanelMouseEntered

    private void loginBarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBarPanelMouseExited
        loginBarPanel.setBackground(new Color(192,192,192));
        loginTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_loginBarPanelMouseExited

    private void loginBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBarPanelMousePressed
        loginBarPanel.setBackground(Color.BLACK);
        loginTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_loginBarPanelMousePressed

    private void loginBarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBarPanelMouseReleased
        loginBarPanel.setBackground(new Color(255,69,0));
        loginTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_loginBarPanelMouseReleased

    private void registerBarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBarPanelMouseEntered
        registerBarPanel.setBackground(new Color(255,69,0));
        registerTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_registerBarPanelMouseEntered

    private void registerBarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBarPanelMouseExited
        registerBarPanel.setBackground(new Color(192,192,192));
        registerTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_registerBarPanelMouseExited

    private void registerBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBarPanelMousePressed
        registerBarPanel.setBackground(Color.BLACK);
        registerTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_registerBarPanelMousePressed

    private void registerBarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBarPanelMouseReleased
        registerBarPanel.setBackground(new Color(255,69,0));
        registerTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_registerBarPanelMouseReleased

    
    public void refreshUsersView() {
        List<User> users = new UserDAO().readComboBox();
        
        loginComboBox.setModel(new DefaultComboBoxModel(users.toArray(new User[0])));
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blackBar1;
    private javax.swing.JPanel blackBar2;
    private javax.swing.JPanel leftBarPanel;
    private javax.swing.JPanel loginBarPanel;
    private javax.swing.JComboBox<String> loginComboBox;
    private javax.swing.JLabel loginTextLabel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel registerBarPanel;
    private javax.swing.JLabel registerTextLabel;
    private javax.swing.JPanel rightBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
