/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import model.bean.User;
import model.dao.UserDAO;
import model.util.PasswordsUtil;
import user_interface.MainFrame;

/**
 *
 * @author Gustavo H. D. Ventura
 */
public class UserDialog extends javax.swing.JFrame {
    
    private int userId;
    private MainFrame mainFrame;
    private User selectedUser;
    private boolean updateMode;
    private UserLoginDialog userLoginDialog;
    
    /**
     * Creates new form UserDialog
     */
    public UserDialog() {
        initComponents();
        configure();
    }
    
    public UserDialog(UserLoginDialog userLoginDialog) {
        initComponents();
        configure();
        
        this.userLoginDialog = userLoginDialog;
        this.updateMode = false;
    }
    
    public UserDialog(int userId, MainFrame mainFrame,  User selectedUser, boolean updateMode) {
        initComponents();
        configure();
        
        this.mainFrame = mainFrame;
        this.selectedUser = selectedUser;
        this.updateMode = updateMode;
        this.userId = userId;
        
        if (updateMode) {
            setTitle("Atualização de Usuário");
            this.mainTitleTextField.setText("Atualização de Usuário");
            
            populateGui(selectedUser);
        }
    }
    
    private void configure() {
        dispose();
        
        setUndecorated(true);
        setDefaultCloseOperation(0);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.loginValidationLabel.setText("_");
        this.passwordValidationLabel.setText("_");
        this.passwordRepeatValidationLabel.setText("_");
        
        pack();
        setLocationRelativeTo(mainFrame);

        setVisible(true);
    }

    private void populateGui(User selectedUser) {
        this.loginTextField.setText(selectedUser.getLogin());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        mainBarPanel = new javax.swing.JPanel();
        loginInputPanel = new javax.swing.JPanel();
        loginTitlePanel = new javax.swing.JPanel();
        loginTitleLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        loginValidationLabel = new javax.swing.JLabel();
        passwordInputPanel = new javax.swing.JPanel();
        passwordTitlePanel = new javax.swing.JPanel();
        passwordTitleLabel = new javax.swing.JLabel();
        passwordValidationLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        midLine = new javax.swing.JPanel();
        passwordRepeatInputPanel = new javax.swing.JPanel();
        passwordRepeatTitlePanel = new javax.swing.JPanel();
        passwordRepeatTitleLabel = new javax.swing.JLabel();
        passwordRepeatValidationLabel = new javax.swing.JLabel();
        passwordRepeatTextField = new javax.swing.JPasswordField();
        confirmPanel = new javax.swing.JPanel();
        confirmTextLabel = new javax.swing.JLabel();
        cancelarPanel = new javax.swing.JPanel();
        cancelarTextLabel = new javax.swing.JLabel();
        midBorderBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(255, 165, 0));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(180, 700));

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        topBarPanel.setBackground(new java.awt.Color(192, 192, 192));

        mainTitleTextField.setBackground(new java.awt.Color(192, 192, 192));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(255, 140, 0));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Cadastro de Usuário");
        mainTitleTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTitleTextField.setPreferredSize(new java.awt.Dimension(165, 110));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainBarPanel.setBackground(new java.awt.Color(211, 211, 211));

        loginInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        loginInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        loginTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        loginTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        loginTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        loginTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        loginTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitleLabel.setText("Nome de usuário");
        loginTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout loginTitlePanelLayout = new javax.swing.GroupLayout(loginTitlePanel);
        loginTitlePanel.setLayout(loginTitlePanelLayout);
        loginTitlePanelLayout.setHorizontalGroup(
            loginTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginTitlePanelLayout.setVerticalGroup(
            loginTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        loginTextField.setBackground(new java.awt.Color(211, 211, 211));
        loginTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginTextField.setForeground(new java.awt.Color(0, 0, 0));
        loginTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        loginValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        loginValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        loginValidationLabel.setText("Nome de usuário inválido *");

        javax.swing.GroupLayout loginInputPanelLayout = new javax.swing.GroupLayout(loginInputPanel);
        loginInputPanel.setLayout(loginInputPanelLayout);
        loginInputPanelLayout.setHorizontalGroup(
            loginInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(loginInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginValidationLabel))
                .addContainerGap())
        );
        loginInputPanelLayout.setVerticalGroup(
            loginInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginInputPanelLayout.createSequentialGroup()
                .addComponent(loginTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        passwordInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        passwordInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        passwordTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        passwordTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        passwordTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        passwordTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordTitleLabel.setText("Senha");
        passwordTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout passwordTitlePanelLayout = new javax.swing.GroupLayout(passwordTitlePanel);
        passwordTitlePanel.setLayout(passwordTitlePanelLayout);
        passwordTitlePanelLayout.setHorizontalGroup(
            passwordTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passwordTitlePanelLayout.setVerticalGroup(
            passwordTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        passwordValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        passwordValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        passwordValidationLabel.setText("Senha inválida *");

        passwordTextField.setBackground(new java.awt.Color(211, 211, 211));
        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(0, 0, 0));
        passwordTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout passwordInputPanelLayout = new javax.swing.GroupLayout(passwordInputPanel);
        passwordInputPanel.setLayout(passwordInputPanelLayout);
        passwordInputPanelLayout.setHorizontalGroup(
            passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInputPanelLayout.createSequentialGroup()
                .addComponent(passwordTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(passwordInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(passwordInputPanelLayout.createSequentialGroup()
                        .addComponent(passwordValidationLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        passwordInputPanelLayout.setVerticalGroup(
            passwordInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordInputPanelLayout.createSequentialGroup()
                .addComponent(passwordTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        midLine.setBackground(new java.awt.Color(0, 0, 0));
        midLine.setForeground(new java.awt.Color(0, 0, 0));
        midLine.setMinimumSize(new java.awt.Dimension(1, 346));
        midLine.setPreferredSize(new java.awt.Dimension(1, 346));

        javax.swing.GroupLayout midLineLayout = new javax.swing.GroupLayout(midLine);
        midLine.setLayout(midLineLayout);
        midLineLayout.setHorizontalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        midLineLayout.setVerticalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        passwordRepeatInputPanel.setBackground(new java.awt.Color(192, 192, 192));

        passwordRepeatTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        passwordRepeatTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        passwordRepeatTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        passwordRepeatTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordRepeatTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordRepeatTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordRepeatTitleLabel.setText("Repetir Senha");
        passwordRepeatTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout passwordRepeatTitlePanelLayout = new javax.swing.GroupLayout(passwordRepeatTitlePanel);
        passwordRepeatTitlePanel.setLayout(passwordRepeatTitlePanelLayout);
        passwordRepeatTitlePanelLayout.setHorizontalGroup(
            passwordRepeatTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordRepeatTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        passwordRepeatTitlePanelLayout.setVerticalGroup(
            passwordRepeatTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordRepeatTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        passwordRepeatValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        passwordRepeatValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordRepeatValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        passwordRepeatValidationLabel.setText("Senha inválida *");

        passwordRepeatTextField.setBackground(new java.awt.Color(211, 211, 211));
        passwordRepeatTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordRepeatTextField.setForeground(new java.awt.Color(0, 0, 0));
        passwordRepeatTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout passwordRepeatInputPanelLayout = new javax.swing.GroupLayout(passwordRepeatInputPanel);
        passwordRepeatInputPanel.setLayout(passwordRepeatInputPanelLayout);
        passwordRepeatInputPanelLayout.setHorizontalGroup(
            passwordRepeatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordRepeatInputPanelLayout.createSequentialGroup()
                .addComponent(passwordRepeatTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(passwordRepeatInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordRepeatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordRepeatInputPanelLayout.createSequentialGroup()
                        .addComponent(passwordRepeatValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(passwordRepeatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        passwordRepeatInputPanelLayout.setVerticalGroup(
            passwordRepeatInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordRepeatInputPanelLayout.createSequentialGroup()
                .addComponent(passwordRepeatTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordRepeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordRepeatValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        confirmPanel.setBackground(new java.awt.Color(192, 192, 192));
        confirmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmPanelMouseReleased(evt);
            }
        });

        confirmTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        confirmTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        confirmTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTextLabel.setText("Confirmar");
        confirmTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cancelarPanel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setForeground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        cancelarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseReleased(evt);
            }
        });

        cancelarTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        cancelarTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarTextLabel.setText("Cancelar");
        cancelarTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cancelarPanelLayout = new javax.swing.GroupLayout(cancelarPanel);
        cancelarPanel.setLayout(cancelarPanelLayout);
        cancelarPanelLayout.setHorizontalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarPanelLayout.setVerticalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midBorderBottom.setBackground(new java.awt.Color(211, 211, 211));
        midBorderBottom.setForeground(new java.awt.Color(211, 211, 211));

        javax.swing.GroupLayout midBorderBottomLayout = new javax.swing.GroupLayout(midBorderBottom);
        midBorderBottom.setLayout(midBorderBottomLayout);
        midBorderBottomLayout.setHorizontalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        midBorderBottomLayout.setVerticalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainBarPanelLayout = new javax.swing.GroupLayout(mainBarPanel);
        mainBarPanel.setLayout(mainBarPanelLayout);
        mainBarPanelLayout.setHorizontalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginInputPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(midLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordRepeatInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        mainBarPanelLayout.setVerticalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(midLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(midBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(passwordInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(passwordRepeatInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(loginInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseEntered
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseEntered

    private void cancelarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseExited
        cancelarPanel.setBackground(new Color(192,192,192));
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMouseExited

    private void cancelarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMousePressed
        cancelarPanel.setBackground(Color.BLACK);
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMousePressed

    private void cancelarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseReleased
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseReleased

    private void cancelarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarPanelMouseClicked

    private void confirmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseEntered
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseEntered

    private void confirmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseExited
        confirmPanel.setBackground(new Color(192,192,192));
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMouseExited

    private void confirmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMousePressed
        confirmPanel.setBackground(Color.BLACK);
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMousePressed

    private void confirmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseReleased
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseReleased

    private void confirmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseClicked
        performAction();
    }//GEN-LAST:event_confirmPanelMouseClicked

    private void performAction() {
        String login = this.loginTextField.getText();
        String password = this.passwordTextField.getText();
        String passwordRepeat = this.passwordRepeatTextField.getText();
        
        //Sugestão:
        //Implementar sistema pra não deixar cadastrar/atualizar para um Login já cadastrado
        
        if (updateMode) {
            User user = this.selectedUser;
            if (!login.equals(user.getLogin()) && password.trim().equals("") && passwordRepeat.trim().equals("")) {
                try {
                    PasswordsUtil.validaLogin(login);
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(UserDialog.this, "Login inválido, é permitido apenas letras alfabéticas.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                user.setLogin(login);
                new UserDAO().updateLogin(user, this.userId);
            } else if (login.equals(user.getLogin()) && !password.trim().equals("") && !passwordRepeat.trim().equals("")) {
                try {
                    PasswordsUtil.validaSenha(password);
                    PasswordsUtil.validaSenha(passwordRepeat);
                    PasswordsUtil.validaEquals(password, passwordRepeat);
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(UserDialog.this, "A senha é inválida.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                user.setPassword(password);
                new UserDAO().updatePassword(user, this.userId);
            } else if (!login.equals(user.getLogin()) && !password.trim().equals("") && !passwordRepeat.trim().equals("")) {
                try {
                    PasswordsUtil.validaLogin(login);
                    PasswordsUtil.validaSenha(password);
                    PasswordsUtil.validaSenha(passwordRepeat);
                    PasswordsUtil.validaEquals(password, passwordRepeat);
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(UserDialog.this, "A senha é inválida.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                user.setLogin(login);
                user.setPassword(password);
                new UserDAO().updateLogin(user, this.userId);
                new UserDAO().updatePassword(user, this.userId);
            }
            mainFrame.refreshView("Usuários", null);
        } else {
            try {
                PasswordsUtil.validaLogin(login);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(UserDialog.this, "Login inválido, é permitido apenas letras alfabéticas.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                PasswordsUtil.validaSenha(password);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(UserDialog.this, "A senha é inválida.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                PasswordsUtil.validaEquals(password, passwordRepeat);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(UserDialog.this, "As senhas não são iguais.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            User user = new User();
            user.setLogin(login);
            user.setPassword(password);
            user.setAdmin(false);

            try {
                new UserDAO().create(user);
                if (mainFrame != null) {
                    this.mainFrame.refreshView("Usuários", null);
                }
            } catch (HeadlessException ex) {
                JOptionPane.showMessageDialog(UserDialog.this, "Erro ao cadastrar usuário: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    if (userLoginDialog != null) {
        userLoginDialog.refreshUsersView();
    }
    setVisible(false);
    dispose();    
    }
    
    public void registerUser(String login, String password, String passwordRepeat) {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserDialog();
                } catch (Exception e) {
                    e.printStackTrace();
                }        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelarPanel;
    private javax.swing.JLabel cancelarTextLabel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel confirmTextLabel;
    private javax.swing.JPanel loginInputPanel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JPanel loginTitlePanel;
    private javax.swing.JLabel loginValidationLabel;
    private javax.swing.JPanel mainBarPanel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPanel midBorderBottom;
    private javax.swing.JPanel midLine;
    private javax.swing.JPanel passwordInputPanel;
    private javax.swing.JPanel passwordRepeatInputPanel;
    private javax.swing.JPasswordField passwordRepeatTextField;
    private javax.swing.JLabel passwordRepeatTitleLabel;
    private javax.swing.JPanel passwordRepeatTitlePanel;
    private javax.swing.JLabel passwordRepeatValidationLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel passwordTitleLabel;
    private javax.swing.JPanel passwordTitlePanel;
    private javax.swing.JLabel passwordValidationLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
