/*
    This file is part of Workshop.

    Workshop is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Workshop is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Workshop. If not, see <https://www.gnu.org/licenses/>

    Contact me:
        Email:   gustavohenrique0008@gmail.com
        Discord: TwoSouls#3428
*/
package user_interface.dialog;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.BorderFactory;
import model.bean.Orcamento;
import model.bean.Veiculo;
import model.dao.VeiculoDAO;
import user_interface.MainFrame;
import user_interface.table_manager.TableManager;

/**
 *
 * @author Gustavo H. D. Ventura
 */
public class VeiculoDialog extends javax.swing.JFrame {
    
    private int userId;
    private MainFrame mainFrame;
    private Veiculo selectedVehicle;
    private boolean updateMode;
    private boolean fromTableManager;
    private Orcamento orcamentoHolder;
    private boolean orcamentoUpdateMode;
    
    /**
     * Creates new form VeiculoDialog
     */
    public VeiculoDialog() {
        initComponents();
        configure();
    }
    
    public VeiculoDialog(int userId, MainFrame mainFrame, Veiculo selectedVehicle, boolean updateMode) {
        initComponents();
        configure();
        setLocationRelativeTo(mainFrame);
        
        this.mainFrame = mainFrame;
        this.selectedVehicle = selectedVehicle;
        this.updateMode = updateMode;
        this.userId = userId;
        this.fromTableManager = false;
        this.orcamentoHolder = null;
        this.orcamentoUpdateMode = false;
        
        if (updateMode) {
            setTitle("Atualização de Veículo");
            this.mainTitleTextField.setText("Atualização de Veículo");
            
            populateGui(selectedVehicle);
        }
    }
    
    public void setFromTableManager(boolean fromTableManager) {
        this.fromTableManager = fromTableManager;
    }
    
    public void setOrcamentoHolder(Orcamento orcamento) {
        this.orcamentoHolder = orcamento;
    }
    
    public void setOrcamentoUpdateMode(boolean orcamentoUpdateMode) {
        this.orcamentoUpdateMode = orcamentoUpdateMode;
    }
    
    private void configure() {
        dispose();
        
        setUndecorated(true);
        setDefaultCloseOperation(0);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.descriptionValidationLabel.setText("_");
        this.fuelLevelValidationLabel.setText("_");
        this.licensePlateValidationLabel.setText("_");
        this.fuelTypeValidationLabel.setText("_");
        this.colorValidationLabel.setText("_");
        this.mileageValidationLabel.setText("_");
        
        pack();
        
        setVisible(true);
    }

    private void populateGui(Veiculo selectedVehicle) {
        this.fuelLevelTextField.setText(selectedVehicle.getMarcador());
        this.descriptionTextField.setText(selectedVehicle.getDescricao());
        this.fuelTypeTextField.setText(selectedVehicle.getCombustivel());
        this.licensePlateTextField.setText(selectedVehicle.getPlaca());
        this.mileageTextField.setText(selectedVehicle.getQuilometragem());
        this.colorTextField.setText(selectedVehicle.getCor());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        topBarPanel = new javax.swing.JPanel();
        mainTitleTextField = new javax.swing.JLabel();
        mainBarPanel = new javax.swing.JPanel();
        descriptionInputPanel = new javax.swing.JPanel();
        descriptionTitlePanel = new javax.swing.JPanel();
        descriptionTitleLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        descriptionValidationLabel = new javax.swing.JLabel();
        fuelTypeInputPanel = new javax.swing.JPanel();
        fuelTypeTitlePanel = new javax.swing.JPanel();
        fuelTypeTitleLabel = new javax.swing.JLabel();
        fuelTypeTextField = new javax.swing.JTextField();
        fuelTypeValidationLabel = new javax.swing.JLabel();
        midLine = new javax.swing.JPanel();
        licensePlateInputPanel = new javax.swing.JPanel();
        licensePlateTitlePanel = new javax.swing.JPanel();
        licensePlateTitleLabel = new javax.swing.JLabel();
        licensePlateTextField = new javax.swing.JTextField();
        licensePlateValidationLabel = new javax.swing.JLabel();
        mileageInputPanel = new javax.swing.JPanel();
        mileageTitlePanel = new javax.swing.JPanel();
        mileageTitleLabel = new javax.swing.JLabel();
        mileageValidationLabel = new javax.swing.JLabel();
        mileageTextField = new javax.swing.JTextField();
        confirmPanel = new javax.swing.JPanel();
        confirmTextLabel = new javax.swing.JLabel();
        cancelarPanel = new javax.swing.JPanel();
        cancelarTextLabel = new javax.swing.JLabel();
        midBorderBottom = new javax.swing.JPanel();
        colorInputPanel = new javax.swing.JPanel();
        colorTitlePanel = new javax.swing.JPanel();
        colorTitleLabel = new javax.swing.JLabel();
        colorTextField = new javax.swing.JTextField();
        colorValidationLabel = new javax.swing.JLabel();
        fuelLevelInputPanel = new javax.swing.JPanel();
        fuelLevelTitlePanel = new javax.swing.JPanel();
        fuelLevelTitleLabel = new javax.swing.JLabel();
        fuelLevelValidationLabel = new javax.swing.JLabel();
        fuelLevelTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Veículo");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        sideBarPanel.setBackground(new java.awt.Color(255, 165, 0));
        sideBarPanel.setPreferredSize(new java.awt.Dimension(180, 700));

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        topBarPanel.setBackground(new java.awt.Color(192, 192, 192));

        mainTitleTextField.setBackground(new java.awt.Color(192, 192, 192));
        mainTitleTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainTitleTextField.setForeground(new java.awt.Color(255, 140, 0));
        mainTitleTextField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleTextField.setText("Cadastro de Veículo");
        mainTitleTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainTitleTextField.setPreferredSize(new java.awt.Dimension(165, 110));

        javax.swing.GroupLayout topBarPanelLayout = new javax.swing.GroupLayout(topBarPanel);
        topBarPanel.setLayout(topBarPanelLayout);
        topBarPanelLayout.setHorizontalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        topBarPanelLayout.setVerticalGroup(
            topBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainBarPanel.setBackground(new java.awt.Color(211, 211, 211));

        descriptionInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        descriptionInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        descriptionTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        descriptionTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        descriptionTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        descriptionTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionTitleLabel.setText("Descrição");
        descriptionTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout descriptionTitlePanelLayout = new javax.swing.GroupLayout(descriptionTitlePanel);
        descriptionTitlePanel.setLayout(descriptionTitlePanelLayout);
        descriptionTitlePanelLayout.setHorizontalGroup(
            descriptionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        descriptionTitlePanelLayout.setVerticalGroup(
            descriptionTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        descriptionTextField.setBackground(new java.awt.Color(211, 211, 211));
        descriptionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTextField.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        descriptionValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        descriptionValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descriptionValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        descriptionValidationLabel.setText("Descrição inválida *");

        javax.swing.GroupLayout descriptionInputPanelLayout = new javax.swing.GroupLayout(descriptionInputPanel);
        descriptionInputPanel.setLayout(descriptionInputPanelLayout);
        descriptionInputPanelLayout.setHorizontalGroup(
            descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(descriptionInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionValidationLabel))
                .addContainerGap())
        );
        descriptionInputPanelLayout.setVerticalGroup(
            descriptionInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionInputPanelLayout.createSequentialGroup()
                .addComponent(descriptionTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        fuelTypeInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        fuelTypeInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        fuelTypeTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        fuelTypeTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        fuelTypeTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        fuelTypeTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelTypeTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        fuelTypeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelTypeTitleLabel.setText("Combustível");
        fuelTypeTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout fuelTypeTitlePanelLayout = new javax.swing.GroupLayout(fuelTypeTitlePanel);
        fuelTypeTitlePanel.setLayout(fuelTypeTitlePanelLayout);
        fuelTypeTitlePanelLayout.setHorizontalGroup(
            fuelTypeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelTypeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fuelTypeTitlePanelLayout.setVerticalGroup(
            fuelTypeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelTypeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        fuelTypeTextField.setBackground(new java.awt.Color(211, 211, 211));
        fuelTypeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fuelTypeTextField.setForeground(new java.awt.Color(0, 0, 0));
        fuelTypeTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        fuelTypeValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        fuelTypeValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fuelTypeValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        fuelTypeValidationLabel.setText("Combustível inválido *");

        javax.swing.GroupLayout fuelTypeInputPanelLayout = new javax.swing.GroupLayout(fuelTypeInputPanel);
        fuelTypeInputPanel.setLayout(fuelTypeInputPanelLayout);
        fuelTypeInputPanelLayout.setHorizontalGroup(
            fuelTypeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelTypeTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fuelTypeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fuelTypeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuelTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(fuelTypeInputPanelLayout.createSequentialGroup()
                        .addComponent(fuelTypeValidationLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fuelTypeInputPanelLayout.setVerticalGroup(
            fuelTypeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelTypeInputPanelLayout.createSequentialGroup()
                .addComponent(fuelTypeTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuelTypeValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        midLine.setBackground(new java.awt.Color(0, 0, 0));
        midLine.setForeground(new java.awt.Color(0, 0, 0));
        midLine.setMinimumSize(new java.awt.Dimension(1, 346));
        midLine.setPreferredSize(new java.awt.Dimension(1, 346));

        javax.swing.GroupLayout midLineLayout = new javax.swing.GroupLayout(midLine);
        midLine.setLayout(midLineLayout);
        midLineLayout.setHorizontalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        midLineLayout.setVerticalGroup(
            midLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        licensePlateInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        licensePlateInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        licensePlateTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        licensePlateTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        licensePlateTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        licensePlateTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        licensePlateTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        licensePlateTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licensePlateTitleLabel.setText("Placa");
        licensePlateTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout licensePlateTitlePanelLayout = new javax.swing.GroupLayout(licensePlateTitlePanel);
        licensePlateTitlePanel.setLayout(licensePlateTitlePanelLayout);
        licensePlateTitlePanelLayout.setHorizontalGroup(
            licensePlateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(licensePlateTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        licensePlateTitlePanelLayout.setVerticalGroup(
            licensePlateTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(licensePlateTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        licensePlateTextField.setBackground(new java.awt.Color(211, 211, 211));
        licensePlateTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        licensePlateTextField.setForeground(new java.awt.Color(0, 0, 0));
        licensePlateTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        licensePlateValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        licensePlateValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        licensePlateValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        licensePlateValidationLabel.setText("Placa inválida *");

        javax.swing.GroupLayout licensePlateInputPanelLayout = new javax.swing.GroupLayout(licensePlateInputPanel);
        licensePlateInputPanel.setLayout(licensePlateInputPanelLayout);
        licensePlateInputPanelLayout.setHorizontalGroup(
            licensePlateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(licensePlateTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(licensePlateInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(licensePlateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licensePlateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(licensePlateValidationLabel))
                .addContainerGap())
        );
        licensePlateInputPanelLayout.setVerticalGroup(
            licensePlateInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licensePlateInputPanelLayout.createSequentialGroup()
                .addComponent(licensePlateTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(licensePlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licensePlateValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        mileageInputPanel.setBackground(new java.awt.Color(192, 192, 192));

        mileageTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        mileageTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        mileageTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        mileageTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mileageTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        mileageTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mileageTitleLabel.setText("Quilometragem");
        mileageTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout mileageTitlePanelLayout = new javax.swing.GroupLayout(mileageTitlePanel);
        mileageTitlePanel.setLayout(mileageTitlePanelLayout);
        mileageTitlePanelLayout.setHorizontalGroup(
            mileageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mileageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mileageTitlePanelLayout.setVerticalGroup(
            mileageTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mileageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mileageValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        mileageValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mileageValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        mileageValidationLabel.setText("Quilometragem inválida *");

        mileageTextField.setBackground(new java.awt.Color(211, 211, 211));
        mileageTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mileageTextField.setForeground(new java.awt.Color(0, 0, 0));
        mileageTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout mileageInputPanelLayout = new javax.swing.GroupLayout(mileageInputPanel);
        mileageInputPanel.setLayout(mileageInputPanelLayout);
        mileageInputPanelLayout.setHorizontalGroup(
            mileageInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mileageInputPanelLayout.createSequentialGroup()
                .addComponent(mileageTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mileageInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mileageInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mileageInputPanelLayout.createSequentialGroup()
                        .addComponent(mileageValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mileageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mileageInputPanelLayout.setVerticalGroup(
            mileageInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mileageInputPanelLayout.createSequentialGroup()
                .addComponent(mileageTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mileageValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        confirmPanel.setBackground(new java.awt.Color(192, 192, 192));
        confirmPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmPanelMouseReleased(evt);
            }
        });

        confirmTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        confirmTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        confirmTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmTextLabel.setText("Confirmar");
        confirmTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(confirmTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cancelarPanel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setForeground(new java.awt.Color(192, 192, 192));
        cancelarPanel.setPreferredSize(new java.awt.Dimension(290, 40));
        cancelarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelarPanelMouseReleased(evt);
            }
        });

        cancelarTextLabel.setBackground(new java.awt.Color(192, 192, 192));
        cancelarTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarTextLabel.setForeground(new java.awt.Color(255, 140, 0));
        cancelarTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarTextLabel.setText("Cancelar");
        cancelarTextLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout cancelarPanelLayout = new javax.swing.GroupLayout(cancelarPanel);
        cancelarPanel.setLayout(cancelarPanelLayout);
        cancelarPanelLayout.setHorizontalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarPanelLayout.setVerticalGroup(
            cancelarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midBorderBottom.setBackground(new java.awt.Color(211, 211, 211));
        midBorderBottom.setForeground(new java.awt.Color(211, 211, 211));

        javax.swing.GroupLayout midBorderBottomLayout = new javax.swing.GroupLayout(midBorderBottom);
        midBorderBottom.setLayout(midBorderBottomLayout);
        midBorderBottomLayout.setHorizontalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        midBorderBottomLayout.setVerticalGroup(
            midBorderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        colorInputPanel.setBackground(new java.awt.Color(192, 192, 192));
        colorInputPanel.setPreferredSize(new java.awt.Dimension(290, 116));

        colorTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        colorTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        colorTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        colorTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        colorTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        colorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorTitleLabel.setText("Cor");
        colorTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout colorTitlePanelLayout = new javax.swing.GroupLayout(colorTitlePanel);
        colorTitlePanel.setLayout(colorTitlePanelLayout);
        colorTitlePanelLayout.setHorizontalGroup(
            colorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        colorTitlePanelLayout.setVerticalGroup(
            colorTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        colorTextField.setBackground(new java.awt.Color(211, 211, 211));
        colorTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        colorTextField.setForeground(new java.awt.Color(0, 0, 0));
        colorTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        colorValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        colorValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        colorValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        colorValidationLabel.setText("Cor inválida *");

        javax.swing.GroupLayout colorInputPanelLayout = new javax.swing.GroupLayout(colorInputPanel);
        colorInputPanel.setLayout(colorInputPanelLayout);
        colorInputPanelLayout.setHorizontalGroup(
            colorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(colorInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(colorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorValidationLabel))
                .addContainerGap())
        );
        colorInputPanelLayout.setVerticalGroup(
            colorInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorInputPanelLayout.createSequentialGroup()
                .addComponent(colorTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        fuelLevelInputPanel.setBackground(new java.awt.Color(192, 192, 192));

        fuelLevelTitlePanel.setBackground(new java.awt.Color(255, 165, 0));
        fuelLevelTitlePanel.setPreferredSize(new java.awt.Dimension(290, 40));

        fuelLevelTitleLabel.setBackground(new java.awt.Color(255, 165, 0));
        fuelLevelTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelLevelTitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        fuelLevelTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelLevelTitleLabel.setText("Marcador");
        fuelLevelTitleLabel.setPreferredSize(new java.awt.Dimension(290, 40));

        javax.swing.GroupLayout fuelLevelTitlePanelLayout = new javax.swing.GroupLayout(fuelLevelTitlePanel);
        fuelLevelTitlePanel.setLayout(fuelLevelTitlePanelLayout);
        fuelLevelTitlePanelLayout.setHorizontalGroup(
            fuelLevelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelLevelTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fuelLevelTitlePanelLayout.setVerticalGroup(
            fuelLevelTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fuelLevelTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        fuelLevelValidationLabel.setBackground(new java.awt.Color(192, 192, 192));
        fuelLevelValidationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fuelLevelValidationLabel.setForeground(new java.awt.Color(255, 99, 71));
        fuelLevelValidationLabel.setText("Marcador inválido *");

        fuelLevelTextField.setBackground(new java.awt.Color(211, 211, 211));
        fuelLevelTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fuelLevelTextField.setForeground(new java.awt.Color(0, 0, 0));
        fuelLevelTextField.setPreferredSize(new java.awt.Dimension(266, 30));

        javax.swing.GroupLayout fuelLevelInputPanelLayout = new javax.swing.GroupLayout(fuelLevelInputPanel);
        fuelLevelInputPanel.setLayout(fuelLevelInputPanelLayout);
        fuelLevelInputPanelLayout.setHorizontalGroup(
            fuelLevelInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelLevelInputPanelLayout.createSequentialGroup()
                .addComponent(fuelLevelTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(fuelLevelInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fuelLevelInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fuelLevelInputPanelLayout.createSequentialGroup()
                        .addComponent(fuelLevelValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fuelLevelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fuelLevelInputPanelLayout.setVerticalGroup(
            fuelLevelInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelLevelInputPanelLayout.createSequentialGroup()
                .addComponent(fuelLevelTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuelLevelValidationLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainBarPanelLayout = new javax.swing.GroupLayout(mainBarPanel);
        mainBarPanel.setLayout(mainBarPanelLayout);
        mainBarPanelLayout.setHorizontalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainBarPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licensePlateInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(midLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midBorderBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuelTypeInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mileageInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelLevelInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        mainBarPanelLayout.setVerticalGroup(
            mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainBarPanelLayout.createSequentialGroup()
                                .addComponent(fuelTypeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mileageInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fuelLevelInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainBarPanelLayout.createSequentialGroup()
                                .addComponent(licensePlateInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptionInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(mainBarPanelLayout.createSequentialGroup()
                        .addComponent(midLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(midBorderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseEntered
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseEntered

    private void cancelarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseExited
        cancelarPanel.setBackground(new Color(192,192,192));
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMouseExited

    private void cancelarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMousePressed
        cancelarPanel.setBackground(Color.BLACK);
        cancelarTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_cancelarPanelMousePressed

    private void cancelarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseReleased
        cancelarPanel.setBackground(new Color(255,69,0));
        cancelarTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_cancelarPanelMouseReleased

    private void cancelarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPanelMouseClicked
        if (fromTableManager) {
            TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true);
            tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
            tableManager.refreshViewVehicles(this.mainFrame, tableManager.getTable());

            tableManager.pack();
            tableManager.setLocationRelativeTo(this.mainFrame);
            dispose(); 
            tableManager.setVisible(true);
        }

        dispose();
    }//GEN-LAST:event_cancelarPanelMouseClicked

    private void confirmPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseEntered
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseEntered

    private void confirmPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseExited
        confirmPanel.setBackground(new Color(192,192,192));
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMouseExited

    private void confirmPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMousePressed
        confirmPanel.setBackground(Color.BLACK);
        confirmTextLabel.setForeground(new Color(255,140,0));
    }//GEN-LAST:event_confirmPanelMousePressed

    private void confirmPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseReleased
        confirmPanel.setBackground(new Color(255,69,0));
        confirmTextLabel.setForeground(new Color(255,160,122));
    }//GEN-LAST:event_confirmPanelMouseReleased

    private void confirmPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPanelMouseClicked
        performAction();
    }//GEN-LAST:event_confirmPanelMouseClicked

    private void performAction() {
        String description = this.descriptionTextField.getText();
        String fuelType = this.fuelTypeTextField.getText();
        String licensePlate = this.licensePlateTextField.getText();
        String mileage = this.mileageTextField.getText();
        String color = this.colorTextField.getText();
        String fuelLevel = this.fuelLevelTextField.getText();
        
        Veiculo vehicle = null;
        if (updateMode) {
            vehicle = this.selectedVehicle;
        } else {
            vehicle = new Veiculo();
        }
        
        boolean invalidInput = false;
        try {
            vehicle.setPlaca(licensePlate);
            this.licensePlateValidationLabel.setText("_");
        } catch (Exception e) {
            this.licensePlateValidationLabel.setText("O máximo de caracteres para placa é: 15 *");
            invalidInput = true;
        }
        try {
            vehicle.setDescricao(description);
            this.descriptionValidationLabel.setText("_");
        } catch (IllegalArgumentException e) {
            this.descriptionValidationLabel.setText("O máximo de caracteres para descrição é: 74 *");
            invalidInput = true;
        } catch (NullPointerException e) {
            this.descriptionValidationLabel.setText("É preciso inserir uma descrição do veículo. *");
            invalidInput = true;
        }
        try {
            vehicle.setCombustivel(fuelType);
            this.fuelTypeValidationLabel.setText("_");
        } catch (Exception e) {
            this.fuelTypeValidationLabel.setText("O máximo de caracteres para combustível é: 17 *");
            invalidInput = true;
        }
        try {
            vehicle.setCor(color);
            this.colorValidationLabel.setText("_");
        } catch (Exception e) {
            this.colorValidationLabel.setText("O máximo de caracteres para cor é: 13 *");
            invalidInput = true;
        }
        try {
            vehicle.setMarcador(fuelLevel);
            this.fuelLevelValidationLabel.setText("_");
        } catch (Exception e) {
            this.fuelLevelValidationLabel.setText("O máximo de caracteres para marcador é: 9 *");
            invalidInput = true;
        }
        try {
            vehicle.setQuilometragem(mileage);
            this.mileageValidationLabel.setText("_");
        } catch (Exception e) {
            this.mileageValidationLabel.setText("O máximo de caracteres para KM é: 9 *");
            invalidInput = true;
        }
        
        if (invalidInput) {
            return;
        }
        
        try {
            if (this.updateMode) {           
                new VeiculoDAO().update(vehicle, userId);
            } else {
                new VeiculoDAO().create(vehicle);
            }
            
            if (mainFrame != null && !fromTableManager) {
                this.mainFrame.refreshView("Veículos", null);
                dispose();
            } else {
                TableManager tableManager = new TableManager(this.userId, this.mainFrame, this.orcamentoHolder, new javax.swing.JFrame(), true);
                tableManager.setOrcamentoUpdateMode(this.orcamentoUpdateMode);
                tableManager.refreshViewVehicles(this.mainFrame, tableManager.getTable());

                tableManager.pack();
                tableManager.setLocationRelativeTo(this.mainFrame);
                dispose(); 
                tableManager.setVisible(true);
            }
        } catch (HeadlessException ex) {
            System.err.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiculoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiculoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiculoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiculoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VeiculoDialog();
                } catch (Exception e) {
                    e.printStackTrace();
                }        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelarPanel;
    private javax.swing.JLabel cancelarTextLabel;
    private javax.swing.JPanel colorInputPanel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel colorTitleLabel;
    private javax.swing.JPanel colorTitlePanel;
    private javax.swing.JLabel colorValidationLabel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel confirmTextLabel;
    private javax.swing.JPanel descriptionInputPanel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel descriptionTitleLabel;
    private javax.swing.JPanel descriptionTitlePanel;
    private javax.swing.JLabel descriptionValidationLabel;
    private javax.swing.JPanel fuelLevelInputPanel;
    private javax.swing.JTextField fuelLevelTextField;
    private javax.swing.JLabel fuelLevelTitleLabel;
    private javax.swing.JPanel fuelLevelTitlePanel;
    private javax.swing.JLabel fuelLevelValidationLabel;
    private javax.swing.JPanel fuelTypeInputPanel;
    private javax.swing.JTextField fuelTypeTextField;
    private javax.swing.JLabel fuelTypeTitleLabel;
    private javax.swing.JPanel fuelTypeTitlePanel;
    private javax.swing.JLabel fuelTypeValidationLabel;
    private javax.swing.JPanel licensePlateInputPanel;
    private javax.swing.JTextField licensePlateTextField;
    private javax.swing.JLabel licensePlateTitleLabel;
    private javax.swing.JPanel licensePlateTitlePanel;
    private javax.swing.JLabel licensePlateValidationLabel;
    private javax.swing.JPanel mainBarPanel;
    private javax.swing.JLabel mainTitleTextField;
    private javax.swing.JPanel midBorderBottom;
    private javax.swing.JPanel midLine;
    private javax.swing.JPanel mileageInputPanel;
    private javax.swing.JTextField mileageTextField;
    private javax.swing.JLabel mileageTitleLabel;
    private javax.swing.JPanel mileageTitlePanel;
    private javax.swing.JLabel mileageValidationLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
